name: todoapp
description: A modern, smart To-Do App with AI-powered features and sleek UI/UX
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  flutter_local_notifications: ^19.4.0 
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
