name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Cache Pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Get Flutter packages
        run: flutter pub get

      - name: Ensure CocoaPods is installed
        run: |
          set -e
          if ! command -v pod >/dev/null; then
            echo "CocoaPods not found, installing via Homebrew..."
            brew install cocoapods
          else
            echo "CocoaPods already installed: $(pod --version)"
          fi

      - name: Cache CocoaPods repos
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-cocoapods-${{ hashFiles('ios/Podfile.lock') }}

      # Clean Podfile.lock and install CocoaPods (do not modify Podfile in CI)
      - name: Install iOS pods
        run: |
          set -e
          rm -f ios/Podfile.lock
          cd ios
          pod repo update || true
          pod install --repo-update
          cd ..
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Show build outputs for debugging
        if: failure()
        run: |
          echo "Build failed - list build/ios contents"
          ls -la build || true
          ls -la build/ios || true
      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
