name: Build iOS IPA (Flutter + Supabase)

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          channel: stable
          cache: true

      - run: flutter pub get

      - name: Prepare iOS Pods
        run: |
          cd ios
          pod repo update
          pod install

      - run: flutter precache --ios
      - run: |
          cd ios
          pod repo update
          pod install

      # Build .app without codesign
      - run: flutter build ios --release --no-codesign

      # Create Payload folder and move .app inside
      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app Payload
        working-directory: build/ios/iphoneos

      # Zip Payload as .ipa
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Upload IPA to GitHub Release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
